### ISSUE TITLE
How to Use S3 Plugin

### ISSUE THREAD

**Issue by tquin** [tap-ir/tapir#1]
Hi,

Is there any information available about how to use the S3 plugin? From my understanding there is no bash script like `xlocal` for it,  I couldn't find a way to run it from the Python shell or the npm frontend, and it doesn't seem to be a `--features` compile flag.

Is there a preferred way to local an S3 bucket into TAPIR?
Thanks!

**Comment by vertrex** [comment]
Hi, 

The s3 plugin should be included in the server if you compile from sources. 

Here you can see the list of imported plugins : https://github.com/tap-ir/tapir/blob/013327764cea04ad8d8c2f26621e25b37d58e9d8/src/bin/tapir.rs#L107

There is no command line for the s3 plugin yet, the plugin is in 'beta' stage and one only tested a long time ago with a local minio server, if you use it I would be happy to know how it behave, but keep it mind that to achieve full speed it's better to have file stored in the nvme drive on the server. 

To test if a plugin is included in the server you can run the ```xplugins``` command that list all the plugins, also you can run the ```xplugin s3``` it will reply 'not found' if the plugin is not included or it will reply a JSON schema with the argument that the plugin take as input. 

The plugin should be available on the NPM frontend in the 'input' category :

![tapir](https://user-images.githubusercontent.com/14775231/212666979-4eacccdd-6b1f-41a5-af32-ded2aa3fa687.jpg)

however there is an 'issue' at the moment you can only launch plugin by right clicking on a loaded file, so if no file was loaded with ```xlocal``` you can't launch a as you can't right click on a file as there no file appear on the browser. (On the NPM frontend you can go to the ```plugins``` tab to show the list of loaded plugins on the server `S3` should also appear here.)

If needed I will write a command line launcher for the s3 plugin as soon as I can.

**Comment by tquin** [comment]
Hey, thank you, that all makes sense. There's no rush to develop the CLI, I'm asking more out of testing/learning. I'll close this issue out as that answers my question perfectly. Cheers!
